--TRANSACCIONES PARA CAMBIAR
BEGIN TRAN
	UPDATE paciente SET telefono = 444 WHERE Apellido = 'Perez'
if @@ROWCOUNT = 1			--cuantos registros se modificaron
	COMMIT TRAN
ELSE
	ROLLBACK TRAN

--ODTIENE LO REGRISTOS QUE CONSIDEN EN ANBAS TABLAS
SELECT * FROM paciente P
INNER JOIN TurnoPaciente T
ON T.idPaciente = P.IdPaciente
--ODTIENE LOS REGRITROS DE LA TABLA A QUE CONCIDEN EN LA TABLA B
SELECT * FROM paciente P
LEFT JOIN TurnoPaciente T
ON T.idPaciente = P.IdPaciente
--ODTIENE LOS REGRITROS DE LA TABLA B QUE CONCIDEN EN LA TABLA A
SELECT * FROM paciente P
RIGHT JOIN TurnoPaciente T
ON T.idPaciente = P.IdPaciente

--UNE LOS RESULTADOS EN UNA SOLA CONSULTA 
SELECT * FROM Turno
UNION ALL
SELECT * FROM Turno

